# Generated by Django 4.1.7 on 2023-03-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffers',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Hot', 'Hot'), ('Premium', 'Premium'), ('Sponsored', 'Sponsored')], default='Hot', max_length=50),
        ),
    ]
