# Generated by Django 4.1.7 on 2023-03-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_prioducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Subcategories',
            field=models.ManyToManyField(blank=True, null=True, to='product.subcategory'),
        ),
    ]
