# Generated by Django 4.1.7 on 2023-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmanagement', '0002_emailconfig_alter_myuser_is_active_delete_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfig',
            options={'verbose_name_plural': 'Email Configuration'},
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='email_host',
            field=models.CharField(default='mail.tdbsoft.co.ke', max_length=50),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='email_port',
            field=models.CharField(default=465, max_length=5),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='fail_silently',
            field=models.BooleanField(default=True),
        ),
    ]
