# Generated by Django 4.1.7 on 2023-03-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.products')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'cart',
                'db_table': 'cart',
                'managed': True,
            },
        ),
    ]
